# Generated by Django 5.0 on 2024-02-14 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nta1', 'NTA Level 1'), ('nta2', 'NTA Level 2'), ('nta3', 'NTA Level 3'), ('nta4', 'NTA Level 4'), ('nta5', 'NTA Level 5'), ('nta6', 'NTA Level 6'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors'), ('honours', 'Honours'), ('masters', 'Masters'), ('phd', 'PHD')], max_length=15)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='company.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('key_purpose', models.TextField(blank=True, null=True)),
                ('key_result_areas', models.TextField(blank=True, null=True)),
                ('key_knowledge', models.TextField(blank=True, null=True)),
                ('personality_requirements', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('job_grade', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('au', 'AU'), ('b1', 'B1'), ('b2', 'B2'), ('b3', 'B3'), ('b4', 'B4'), ('b5', 'B5'), ('bu', 'BU'), ('c1', 'C1'), ('c2', 'C2'), ('c3', 'C3'), ('c4', 'C4'), ('c5', 'C5'), ('d1', 'D1'), ('d2', 'D2'), ('d3', 'D3'), ('d4', 'D4'), ('d5', 'D5'), ('du', 'DU')], max_length=2)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='company.division')),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='company.position')),
                ('qualification', models.ManyToManyField(related_name='position', to='company.qualification')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['title'], name='company_div_title_37b56e_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['title'], name='company_pos_title_5b2b3f_idx'),
        ),
    ]
